// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.search.model;

import au.gov.nsw.records.search.model.SerieLinkCreatingAgency;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SerieLinkCreatingAgency_Roo_Configurable {
    
    declare @type: SerieLinkCreatingAgency: @Configurable;
    
}
