// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package au.gov.nsw.records.search.model;

import au.gov.nsw.records.search.model.Serie;
import javax.persistence.Entity;

privileged aspect Serie_Roo_Jpa_Entity {
    
    declare @type: Serie: @Entity;
    
}
